#pragma once

#include <cstdint>

#include "game_types.hpp"

// Stability-hook callback typedefs (shared by hooks_stability.cpp and hook_install.cpp)
typedef void (*fn_SetPedPosition_t)(void* self, void* ped);
typedef void (*fn_ManageTasks_t)(void* self);
typedef bool (*fn_IsSimple_t)(void* self);
typedef void (*fn_ScanForAttractorsInRange_t)(void* self, void* ped);
typedef void* (*fn_ControlSubTask_t)(void* self, void* ped);
typedef void* (*fn_PairedAttractorCreateNextSubTask_t)(void* self, void* ped);
typedef void (*fn_FacialDtor_t)(void* self);
typedef void* (*fn_FindActiveTask_t)(void* self, int type);
typedef void (*fn_TaskManagerDestructor_t)(void* self);
typedef void* (*fn_GetPartnerSequence_t)(void* self);
typedef void (*fn_PlayLoadedSound_t)(void* self);
typedef bool (*fn_CheckIfWithinRange_t)(void* self);
typedef void* (*fn_AvoidPedControl_t)(void* self, void* ped);
typedef void (*fn_PlayFootSteps_t)(void* self);
typedef void (*fn_ProcessBuoyancy_t)(void* self);
typedef void (*fn_ProcessStaticCounter_t)(void* self);
typedef bool (*fn_cBuoyancy_ProcessBuoyancy_t)(void* self, void* physical, float f1, void* vec1, void* vec2);
typedef void (*fn_IKManagerProcessPed_t)(void* self, void* ped);
typedef bool (*fn_IsPoliceVehicleInPursuit_t)(int vehicle_index);
typedef void* (*fn_VehiclePursuitAiThunk_t)(void* vehicle);
typedef void (*fn_WanderLookForChatPartners_t)(void* self, void* ped);
typedef int32_t (*fn_u_strlen_t)(const void* s);
typedef void (*fn_SequenceFlush_t)(void* self);
typedef void* (*fn_SequenceCreateNextSubTask_t)(void* self, void* ped);
typedef int (*fn_EventScriptCommandGetPriority_t)(void* self);
typedef void (*fn_FlushTasks_t)(void* self, void* pair, void* ped);
typedef void (*fn_FinishAnimEvasiveStepCB_t)(void* anim, void* context);
typedef void* (*fn_BeInGroupControlSubTask_t)(void* self, void* ped);
typedef void (*fn_IKChainUpdate_t)(void* self, float dt);
typedef bool (*fn_IKChainIsFacingTarget_t)(void* self, void* ped, int index);
typedef void* (*fn_GetSimplestActiveTask_t)(void* self);
typedef void (*fn_ProcessFollowPedSA_t)(void* self, const CVector& target, float f1, float f2, float f3, bool b1);
typedef bool (*fn_LeaveCarMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_GoToPointMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_AchieveHeadingMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_FollowPointRouteMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_KillPedOnFootMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_KillCriminalMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef bool (*fn_FallAndGetUpMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef void* (*fn_PlayHandSignalControlSubTask_t)(void* self, void* ped);
typedef bool (*fn_SimpleAnimMakeAbortable_t)(void* self, void* ped, int priority, void* event);
typedef void (*fn_UpdateCarAI_t)(void* vehicle);
typedef void* (*fn_FacialControlSubTask_t)(void* self, void* ped);
typedef void* (*fn_GetTaskMain_t)(void* self, void* ped);
typedef bool (*fn_GetNearestCarDoor_t)(void* ped, void* vehicle, void* out_vec, int* door_index);

extern fn_SetPedPosition_t g_orig_set_ped_pos;
extern fn_ManageTasks_t g_orig_manage_tasks;
extern fn_ScanForAttractorsInRange_t g_orig_scan_for_attractors_in_range;
extern fn_ControlSubTask_t g_orig_ccgf_control;
extern fn_PairedAttractorCreateNextSubTask_t g_orig_paired_attractor_create_next_sub_task;
extern fn_FacialDtor_t g_orig_facial_dtor;
extern fn_FindActiveTask_t g_orig_find_active_task;
extern fn_TaskManagerDestructor_t g_orig_task_manager_destructor;
extern fn_GetPartnerSequence_t g_orig_partner_greet_get_sequence;
extern fn_PlayLoadedSound_t g_orig_play_loaded_sound;
extern fn_CheckIfWithinRange_t g_orig_check_if_within_range;
extern fn_AvoidPedControl_t g_orig_avoid_ped_control;
extern fn_AddPoliceOccupants_t g_orig_add_police_occupants;
extern fn_PlayFootSteps_t g_orig_play_footsteps;
extern fn_ProcessBuoyancy_t g_orig_process_buoyancy;
extern fn_ProcessStaticCounter_t g_orig_process_static_counter;
extern fn_cBuoyancy_ProcessBuoyancy_t g_orig_cbuoyancy_process_buoyancy;
extern fn_u_strlen_t g_orig_u_strlen;
extern fn_SequenceFlush_t g_orig_sequence_flush;
extern fn_SequenceCreateNextSubTask_t g_orig_sequence_create_next_sub_task;
extern fn_EventScriptCommandGetPriority_t g_orig_event_script_command_get_priority;
extern fn_FlushTasks_t g_orig_flush_tasks;
extern fn_FinishAnimEvasiveStepCB_t g_orig_finish_anim_evasive_step_cb;
extern fn_BeInGroupControlSubTask_t g_orig_be_in_group_control_sub_task;
extern fn_IKChainUpdate_t g_orig_ik_chain_update;
extern fn_ProcessFollowPedSA_t g_orig_process_follow_ped_sa;
extern fn_LeaveCarMakeAbortable_t g_orig_leave_car_make_abortable;
extern fn_UpdateCarAI_t g_orig_update_car_ai;
extern fn_FacialControlSubTask_t g_orig_facial_control_sub_task;
extern fn_GetTaskMain_t g_orig_get_task_main;
extern fn_GetNearestCarDoor_t g_orig_get_nearest_car_door;
extern fn_IKManagerProcessPed_t g_orig_ik_manager_process_ped;
extern fn_IsPoliceVehicleInPursuit_t g_orig_is_police_vehicle_in_pursuit;
extern fn_VehiclePursuitAiThunk_t g_orig_vehicle_pursuit_ai_thunk;
extern fn_WanderLookForChatPartners_t g_orig_wander_look_for_chat_partners;
extern fn_IKChainIsFacingTarget_t g_orig_ik_chain_is_facing_target;
extern fn_GetSimplestActiveTask_t g_orig_get_simplest_active_task;
extern fn_GoToPointMakeAbortable_t g_orig_goto_point_make_abortable;
extern fn_AchieveHeadingMakeAbortable_t g_orig_achieve_heading_make_abortable;
extern fn_FollowPointRouteMakeAbortable_t g_orig_follow_point_route_make_abortable;
extern fn_KillPedOnFootMakeAbortable_t g_orig_kill_ped_on_foot_make_abortable;
extern fn_KillCriminalMakeAbortable_t g_orig_kill_criminal_make_abortable;
extern fn_FallAndGetUpMakeAbortable_t g_orig_fall_and_get_up_make_abortable;
extern fn_PlayHandSignalControlSubTask_t g_orig_play_hand_signal_control_sub_task;
extern fn_SimpleAnimMakeAbortable_t g_orig_simple_anim_make_abortable;

// Stability hook proxies (defined in hooks_stability.cpp, installed from hook_install.cpp)
void proxy_set_ped_pos(void* self, void* ped);
void proxy_manage_tasks(void* self);
void proxy_scan_for_attractors_in_range(void* self, void* ped);
void* proxy_ccgf_control(void* self, void* ped);
void* proxy_paired_attractor_create_next_sub_task(void* self, void* ped);
void proxy_facial_dtor(void* self);
void* proxy_find_active_task(void* self, int type);
void proxy_task_manager_destructor(void* self);
void* proxy_partner_greet_get_sequence(void* self);
void proxy_play_loaded_sound(void* self);
bool proxy_check_if_within_range(void* self);
void* proxy_avoid_ped_control(void* self, void* ped);
void proxy_add_police_occupants(CVehicle* vehicle, bool bSirenOrAlarm);
void proxy_play_footsteps(void* self);
void proxy_process_buoyancy(void* self);
void proxy_process_static_counter(void* self);
bool proxy_cbuoyancy_process_buoyancy(void* self, void* physical, float f1, void* vec1, void* vec2);
int32_t proxy_u_strlen(const void* s);
void proxy_sequence_flush(void* self);
void* proxy_sequence_create_next_sub_task(void* self, void* ped);
int proxy_event_script_command_get_priority(void* self);
void proxy_flush_tasks(void* self, void* pair, void* ped);
void proxy_finish_anim_evasive_step_cb(void* anim, void* context);
void* proxy_be_in_group_control_sub_task(void* self, void* ped);
void proxy_ik_chain_update(void* self, float dt);
void proxy_process_follow_ped_sa(void* self, const CVector& target, float f1, float f2, float f3, bool b1);
bool proxy_leave_car_make_abortable(void* self, void* ped, int priority, void* event);
void proxy_update_car_ai(void* vehicle);
void* proxy_facial_control_sub_task(void* self, void* ped);
void* proxy_get_task_main(void* self, void* ped);
bool proxy_get_nearest_car_door(void* ped, void* vehicle, void* out_vec, int* door_index);
void proxy_ik_manager_process_ped(void* self, void* ped);
bool proxy_is_police_vehicle_in_pursuit(int vehicle_index);
void* proxy_vehicle_pursuit_ai_thunk(void* vehicle);
void proxy_wander_look_for_chat_partners(void* self, void* ped);
bool proxy_ik_chain_is_facing_target(void* self, void* ped, int index);
void* proxy_get_simplest_active_task(void* self);
bool proxy_goto_point_make_abortable(void* self, void* ped, int priority, void* event);
bool proxy_achieve_heading_make_abortable(void* self, void* ped, int priority, void* event);
bool proxy_follow_point_route_make_abortable(void* self, void* ped, int priority, void* event);
bool proxy_kill_ped_on_foot_make_abortable(void* self, void* ped, int priority, void* event);
bool proxy_kill_criminal_make_abortable(void* self, void* ped, int priority, void* event);
bool proxy_fall_and_get_up_make_abortable(void* self, void* ped, int priority, void* event);
void* proxy_play_hand_signal_control_sub_task(void* self, void* ped);
bool proxy_simple_anim_make_abortable(void* self, void* ped, int priority, void* event);