mod buoyancy_gate;
mod config;
mod control_sub_task_gate;
mod inline;
mod causation;
mod civilian_report;
mod event_perception;
mod event_scan_gate;
mod gate;
mod install;
mod lifecycle;
mod runtime;
mod scripts;
mod spawn;
mod static_counter_gate;
mod wanted_population;
mod witness;
mod witness_scan;

pub use config::{HOOKS_ENABLED, MOD_LOGIC_ENABLED};
pub use install::install_lifecycle_hooks;
pub use runtime::{with_runtime, DispatchRuntime};